export const CHANGE_PSEUDO_ACTION = "CHANGE_PSEUDO_ACTION"
export const CHANGE_PASSWORD_ACTION = "CHANGE_PASSWORD_ACTION"
export const LOGIN_ACTION = "LOGIN_ACTION"
export const SHOW_PASSWORD_ACTION = "SHOW_PASSWORD_ACTIONS"

export const CHANGE_DASHBOARD_PAGE_ACTION = "CHANGE_DASHBOARD_PAGE_ACTION"
export const LOGOUT_ACTION = "LOGOUT_ACTION"

export const GET_STATISTICS_ACTION = "GET_STATISTICS_ACTION"

export const GET_SPECIFIC_SURVEY_ACTION = "GET_SPECIFIC_SURVEY_ACTION"

export const GET_SONDAGE_DATA_ACTION = "GET_SONDAGE_DATA_ACTION"
export const GET_GROUP_DATA_ACTION = "GET_GROUP_DATA_ACTION"
export const CHANGE_SONDAGE_SELECTION_ACTION = "CHANGE_SONDAGE_SELECTION_ACTION"
export const CHANGE_GROUP_SELECTION_ACTION = "CHANGE_GROUP_SELECTION_ACTION"
export const POST_SURVEY_ACTION = "POST_SURVEY_ACTION"
export const GET_KEYWORDS_ACTION = "GET_KEYWORDS_ACTION"

export const POST_USERS_ACTION = "POST_USERS_ACTION"
export const POST_GROUP_ACTION = "POST_GROUP_ACTION"
export const CHANGE_USER_GROUP_ACTION = "CHANGE_USER_GROUP_ACTION"
export const CLOSE_SUCCESS_MESSAGE_ACTION = "CLOSE_SUCCESS_MESSAGE_ACTION"
export const GET_ALL_USERS_ACTION = "GET_ALL_USERS_ACTION"
export const CHECK_USER_ACTION = "CHECK_USER_ACTION"
